{{- if and .Values.ingress.enabled .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "enac-ai-reviewer.fullname" . }}-admin
  labels:
    {{- include "enac-ai-reviewer.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- with .Values.ingress.admin.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.admin.path | quote }}
            pathType: {{ .Values.ingress.admin.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ include "enac-ai-reviewer.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
{{- end }}
